AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
  
Style/ClassVars:
  Enabled: false

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 20
